SET search_path TO SIANGBANG;
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('1','Lab',48);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('2','Lab',59);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('3','Lab',27);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('4','Ruangan kelas',65);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('5','Lab',99);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('6','Ruangan kelas',38);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('7','Ruangan kelas',98);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('8','Ruangan kelas',96);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('9','Lab',73);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('10','Lab',47);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('11','Lab',39);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('12','Lab',3);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('13','Lab',28);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('14','Lab',85);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('15','Ruangan kelas',72);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('16','Ruangan kelas',66);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('17','Lab',17);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('18','Ruangan kelas',82);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('19','Ruangan kelas',5);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('20','Ruangan kelas',81);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('21','Lab',83);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('22','Ruangan kelas',21);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('23','Lab',92);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('24','Ruangan kelas',74);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('25','Ruangan kelas',31);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('26','Lab',13);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('27','Ruangan kelas',99);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('28','Lab',43);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('29','Lab',56);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('30','Ruangan kelas',92);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('31','Lab',77);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('32','Ruangan kelas',69);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('33','Lab',63);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('34','Ruangan kelas',70);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('35','Ruangan kelas',14);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('36','Ruangan kelas',49);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('37','Lab',89);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('38','Lab',58);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('39','Ruangan kelas',39);
INSERT INTO RUANGAN_INDOOR(no_ruangan,jenis_indoor,kapasitas) VALUES ('40','Lab',51);
